project:
  type: website 
  output-dir: "."
  
website:
  title: ""
  # favicon: img/favicon.ico
  description: 'A collection of data analytics by Byeong-Hak Choe'
  reader-mode: false
  back-to-top-navigation: true

  navbar:
    background: "#1c4982"
    logo: img/geneseo-logo-squared.png
    pinned: true
    right:
      - text: 🚀 Lecture
        href: listing-danl-299-lec.qmd
      - text: ' '
      - text: ⌨️ Classwork
        href: listing-danl-299-cw.qmd
      - text: ' '
      - text: 💻 Homework
        href: listing-danl-299-hw.qmd
      - text: ' '
      - icon: github
        href: https://github.com/bcdanl/299-code
        target: _blank
      - text: " "
    
  sidebar:
    style: docked
    search: false
    collapse-level: 0
    contents:
      - text: 🏠 Home
        href: index.qmd
      - text: 📓 Syllabus
        href: syllabus.qmd
      - text: 🅱 Brightspace
        href: https://mylearning.suny.edu/d2l/home/2232615
        target: _blank
        
      - text: ✍️️ Project
        href: danl-rw/danl-299-project.qmd
                
      - section: 🗓️ Weeks
        contents:
          - text: Week 01
            href: danl-wk/wk-01.qmd
          - text: Week 02
            href: danl-wk/wk-02.qmd
          - text: Week 03
            href: danl-wk/wk-03.qmd
          - text: Week 04
            href: danl-wk/wk-04.qmd
      
        
  page-footer: 
    border: false
    center: "powered with github, quarto, and rstudio<br>byeong-hak choe, 2025"
    # foreground: dark
    # background: '#9b4e55' 


execute:
  echo: true
  eval: true
  message: false
  warning: false
  
format:
  html: 
    grid:
      margin-width: 400px
      sidebar-width: 200px
    link-external-newwindow: true
    theme:
      light: [flatly]  # flatly litera sandstone 'assets/scss/light.scss'
      dark: [darkly, theme-dark.scss] # darkly cyborg slate solra superhero
    css: [styles.css, assets/css/font.css] # , font.css
    highlight-style: atom-one # espresso   tango
    mainfont:  sans-serif; serif; ui-sans-serif  # Gill Sans, sans-serif;
    include-after-body: [sidebar-button-mobile.html]

