---
title: Classwork 8
subtitle: Scrapping Web-tables with `pd.read_html()`
date: 2025-11-04
execute: 
  eval: false
  echo: false
  warning: false
  message: false
  
from: markdown+emoji
---

```{r}
#| include: false

library(DT)
library(reticulate)
reticulate::use_condaenv("/Users/bchoe/anaconda3", required = TRUE)
```


# Question 1

- Store the table in the following webpage as a `pandas`' `DataFrame`:
  - [Gasoline Pump Components History](https://www.eia.gov/petroleum/gasdiesel/gaspump_hist.php)
	-	Convert the abbreviated month-year string to datetime using `pd.to_datetime()` with `format='%b-%y'`.
  - If necessary, use the `Series.str.replace()` method.
    - For example, `Series.str.replace('A', 'B')` replaces "A" with "B" in `Series`.


```{python}
#| eval: false
Series = pd.to_datetime(Series, format='%b-%y')
```

- Export the `DataFrame` as a CSV file.

*Answer*:
```{python}

```


<br><br>

# Question 2
- Store each table in the following webpage as a `pandas`' `DataFrame`:
  - [https://www.geneseo.edu/business/student%20outcomes](https://www.geneseo.edu/business/student%20outcomes)

- Ensure each table has appropriate column names and properly structured observations.

- Export the `DataFrame` as a CSV file.

*Answer*:
```{python}

```


<br><br>



# Discussion

<font size = "5">Welcome to our Classwork 8 Discussion Board! 👋 </font>


This space is designed for you to engage with your classmates about the material covered in Classwork 8.

Whether you are looking to delve deeper into the content, share insights, or have questions about the content, this is the perfect place for you.

If you have any specific questions for Byeong-Hak (**@bcdanl**) regarding the Classwork 8 materials or need clarification on any points, don't hesitate to ask here. 

All comments will be stored [here](https://github.com/bcdanl/210/discussions/).

Let's collaborate and learn from each other!


